// Guessing Game: Create a C++ program that uses a `do-while` loop to simulate
// a simple guessing game. The program generates a random number between 1 and 
// 100, and the user must guess it. Provide hints such as "too high" or 
// "too low" after each guess. Keep asking until the user guesses correctly.

#include<iostream> 
using namespace std; 

int main() { 
    srand(time(NULL));          // makes the randomization to work by feeding in the random number generator a seed
    int x = rand() % 100 + 1;  // a random number that can be any integer (maybe very large) is generated by rand() function
    cout << x << endl; 
    int c = 0; 
    int guess;

    do { 
        cout << "enter your guess: "; 
        cin >> guess; 
        if (guess > x) { 
            cout << "too high!" << endl; 
        } 
        if (guess < x) { 
            cout << "too low!" << endl; 
        }
        c++; 
    } while (guess != x && c < 5);
    
    if (guess == x) { //  if (guessed)
        cout << "You guessed it!" << endl; 
    } else { 
        cout << "You are out of chances!" << endl; 
    }

    // Alternative solution: 
    // bool guessed = false; 
    // do { 
    //     cout << "enter your guess: "; 
    //     cin >> guess; 
    //     if (guess > x) { 
    //         cout << "too high!" << endl; 
    //     } 
    //     if (guess < x) { 
    //         cout << "too low!" << endl; 
    //     }
    //     if (guess == x) { 
    //         guessed = true; 
    //     }
    //     c++; 
    // } while (guess != x && c < 5);

    // if (guessed == true) { //  if (guessed)
    //     cout << "You guessed it!" << endl; 
    // } else { 
    //     cout << "You are out of chances!" << endl; 
    // }
}
